# Imagem Docker
FROM mcr.microsoft.com/mssql/server:2017-latest

# Instalando depedências e driver ODBC
RUN apt-get update && apt-get install -y unixodbc-dev && apt-get clean

# Diretório padrão
WORKDIR /opt/mssql

# Copiando script de criação de database 
#COPY init-mssql.sh .
#COPY db_mssql.sh .
#COPY db_mssql.sql .

# Expondo porta de conexão MSSQL
EXPOSE 1433
