# Imagem Docker
FROM postgres:14.5
#FROM postgres:13.4

# Copiando script de ciação do database
#COPY postgres/db_postgresql.sh /docker-entrypoint-initdb.d

# Expondo porta de conexão Postgres
EXPOSE 5432
